kg205: remove fields causing apply errors
Error: Resource not found: defaultReviewInviteTemplate
    at /ce/km/field-presentation/restaurant.json 1383:18
Error: Resource not found: facebookParentPageId
    at /ce/km/field-presentation/restaurant.json 1129:18
Error: Resource not found: facebookStoreId
    at /ce/km/field-presentation/restaurant.json 963:18
Error: Resource not found: foursquareLinkedAccount
    at /ce/km/field-presentation/restaurant.json 1117:18